---
name: Postman-endpoint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: cloning app
      run:  |
        git clone https://github.com/4-04-squad/ft_transcendence.git
        cd ./ft_transcendence/project
        sudo apt install -y make
    - uses: SpicyPizza/create-envfile@v1.3
      with:
        DOMAINE: ${{ env.DOMAINE }}
        TITLE: ${{ env.TITLE }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRERS_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        API_HOST: ${{ env.API_HOST }}
        API_PORT: ${{ env.API_PORT }}
        API_URL: ${{ env.API_URL }}
        WEB_HOST: ${{ env.WEB_HOST }}
        WEB_PORT: ${{ env.WEB_PORT }}
        WEB_URL: ${{ env.WEB_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_NAME: ${{ secrets.JWT_NAME }}
        FORTY_TWO_CLIENT_ID: ${{ secrets.FORTY_TWO_CLIENT_ID }}
        FORTY_TWO_CLIENT_SECRET: ${{ secrets.FORTY_TWO_CLIENT_SECRET }}
        ENVIRONMENT: ${{ env.ENVIRONMENT }}
    - name: launch app
      run: make build
    - uses: actions/checkout@v3
    - name: Install Postman CLI
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
    - name: Login to Postman CLI
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
    - name: Run API tests
      run: |
        postman collection run "26253465-2e36fc2b-2d58-45bf-9bd8-57268830bf3c" --integration-id "135708-${{ github.run_id }}"
