---
name: Postman-endpoint

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cloning app
      run:  |
        git clone https://github.com/4-04-squad/ft_transcendence.git
        cd ./ft_transcendence/project
        sudoo apt install -y make
    - name: building app with make
      run:  make build